## Практическая работа

В этой практической работе четыре обязательные задачи.

*Обязательные задачи* нужно сделать для того, чтобы проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении моделей деревьев решений.
2.   Потренироваться в обучении моделей случайного леса. 
3.   Научиться оценивать качество моделей с помошью Accuracy и confusion matrix.
4.   Научиться увеличивать качество моделей с помощью тюнинга параметров.




Что оценивается:

*   Все пункты и критерия приёмки задания выполнены.
*   Удаление колонок по результатам feature_importance и определения типов производится с помощью кода, а не перечислением их вручную.




## Обязательные задачи

### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

0. *Подготовка базовой модели*

Обучите простую модель классификации с помощью DecisionTreeClassifier на данных из датасета vehicles_dataset_prepared.csv. Для этого сделайте следующие шаги:

1. Обучите модель дерева решений с зафиксированным random_state на тренировочной выборке.
2. Сделайте предикт на тестовой выборке.
3. Замерьте точность на тестовой выборке и выведите матрицу ошибок. 
4. Удалите фичи с нулевыми весами по feature_importance из тренировочной и тестовой выборок.
5. Заново обучите модель и измерьте качество.

In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix 

In [2]:
df = pd.read_csv('data/vehicles_dataset_prepared.csv')

df_prepared = df.copy()
df_prepared = df_prepared.drop(['price', 'odometer/price_std'], axis=1)

x = df_prepared.drop(['price_category'], axis=1)
y = df_prepared['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [3]:
# Ваш код здесь
x_train.shape, x_test.shape

((6733, 1460), (2886, 1460))

In [5]:
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
predicted_train = clf.predict(x_train)
predicted_test = clf.predict(x_test)
print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))
confusion_matrix(y_test, predicted_test)

1.0
0.6704781704781705


array([[734,  53, 210],
       [ 45, 681, 227],
       [187, 229, 520]], dtype=int64)

In [12]:
f_imp_list = list(zip(x_train.columns, clf.feature_importances_))
f_imp_list.sort(key = lambda x: x[1], reverse=True)
f_imp_list_droped = [(k, v) for (k,v) in f_imp_list if v == 0]
f_imp_list_droped

[('short_model_-benz', 0.0),
 ('short_model_1', 0.0),
 ('short_model_124', 0.0),
 ('short_model_128i', 0.0),
 ('short_model_135i', 0.0),
 ('short_model_163869', 0.0),
 ('short_model_1928', 0.0),
 ('short_model_1951', 0.0),
 ('short_model_1954', 0.0),
 ('short_model_1960s', 0.0),
 ('short_model_1968', 0.0),
 ('short_model_1972', 0.0),
 ('short_model_1977', 0.0),
 ('short_model_1978', 0.0),
 ('short_model_198.5', 0.0),
 ('short_model_1988', 0.0),
 ('short_model_1994', 0.0),
 ('short_model_1999', 0.0),
 ('short_model_2', 0.0),
 ('short_model_2000', 0.0),
 ('short_model_2002', 0.0),
 ('short_model_2006', 0.0),
 ('short_model_2007', 0.0),
 ('short_model_2008', 0.0),
 ('short_model_2009', 0.0),
 ('short_model_2012', 0.0),
 ('short_model_2015', 0.0),
 ('short_model_2016', 0.0),
 ('short_model_2017', 0.0),
 ('short_model_2018', 0.0),
 ('short_model_210', 0.0),
 ('short_model_240', 0.0),
 ('short_model_2500hd', 0.0),
 ('short_model_280zx', 0.0),
 ('short_model_3', 0.0),
 ('short_model_3-series'

In [15]:
df_prepared_droped = df_prepared.copy()
df_prepared_droped = df_prepared.drop([k for k, v in f_imp_list_droped], axis=1)

x = df_prepared_droped.drop(['price_category'], axis=1)
y = df_prepared_droped['price_category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
x_train.shape, x_test.shape

((6733, 376), (2886, 376))

In [18]:
clf2 = DecisionTreeClassifier()
clf2.fit(x_train, y_train)
predicted_train = clf2.predict(x_train)
predicted_test = clf2.predict(x_test)
print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))
confusion_matrix(y_test, predicted_test)

1.0
0.6760221760221761


array([[753,  52, 192],
       [ 52, 688, 213],
       [195, 231, 510]], dtype=int64)

1. *Подготовка модели случайного леса*

Обучите простую модель классификации с помощью RandomForestClassifier. Для этого сделайте следующие шаги:
1. На новых урезанных семплах тренировочной и тестовой выборок обучите модель случайного леса с зафиксированным random_seed=50.?? 

2. Сделайте предикт и посчитайте точность модели и матрицу ошибок. Сравните с предыдущей моделью дерева решений. Есть ли случаи, когда модель из пункта 1 отрабатывает лучше, чем модель случайного леса?

In [24]:
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [30]:
# Ваш код здесь
rf_clf = RandomForestClassifier(random_state = 50)
rf_clf.fit(x_train, y_train)
predicted_train_rf = rf_clf.predict(x_train)
predicted_test_rf = rf_clf.predict(x_test)
print(accuracy_score(y_train, predicted_train_rf))
print(accuracy_score(y_test, predicted_test_rf))
confusion_matrix(y_test, predicted_test_rf)

1.0
0.7525987525987526


array([[812,  37, 148],
       [ 14, 791, 148],
       [166, 201, 569]], dtype=int64)

In [29]:
(accuracy_score(y_test, predicted_test_rf) - accuracy_score(y_test, predicted_test))

0.07657657657657657

`Модель случайного леса точнее. Исходя из матриц решений можно сделать вывод, что случаев, когда модель из первого пункта работает лучше, чем модель из второго, нет.`

2. *Тюнинг модели случайного леса*

Увеличьте точность модели на тестовом датасете RandomForestClassifier c помощью тюнинга параметров. 

Параметры, которые можно настраивать для увеличения точности:

```
    `bootstrap'
    'max_depth'
    'max_features'
    'min_samples_leaf'
    'min_samples_split'
    'random_state'
    'n_estimators'

```



С описанием каждого из параметров можно ознакомиться в документации:


https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

Задание засчитывается, если значение метрики строго выше 0,76 на тестовом датасете.

In [72]:
# Ваш код здесь
rf_clf_2 = RandomForestClassifier(random_state = 50, n_estimators = 700, min_samples_split = 2, min_samples_leaf = 1, max_features = 'sqrt', max_depth = None, bootstrap = False)
rf_clf_2.fit(x_train, y_train)
predicted_train_rf = rf_clf_2.predict(x_train)
predicted_test_rf = rf_clf_2.predict(x_test)
print(accuracy_score(y_train, predicted_train_rf))
print(accuracy_score(y_test, predicted_test_rf))
confusion_matrix(y_test, predicted_test_rf)

1.0
0.7681912681912682


array([[811,  32, 154],
       [ 12, 798, 143],
       [141, 187, 608]], dtype=int64)

3. *Анализ влияния фичей на модель*

Во всех задачах до вы работали над подготовленным датасетом, где фичи были заранее извлечены из текстовых переменных, отскейлены и пропущены через One Hot Encoder. Сравним, какой была бы предсказательная способность модели, если бы мы использовали только сырые данные из исходного датасета. Для этого проделайте следующие шаги:

1. Загрузите датасет `vehicles_dataset_old.csv`.
2. Удалите из него переменную `price` и все строковые колонки. Дерево решений и случайный лес не умеют самостоятельно работать со строковыми значениями.
3. Сформируйте x_train и x_test так же, как они были сформированы в предыдущих заданиях.
4. Обучите свою лучшую модель случайного леса на новых данных и замерьте качество. Убедитесь, что оно ухудшилось.
5. Найдите три фичи, которые лучшим образом повлияли на предсказательную способность модели.

In [86]:
df_old = pd.read_csv('data/vehicles_dataset_old.csv')
df_old.head()

id                                                url  \
0  7308295377  https://chattanooga.craigslist.org/ctd/d/chatt...   
1  7316380095  https://newjersey.craigslist.org/ctd/d/carlsta...   
2  7313733749  https://reno.craigslist.org/ctd/d/atlanta-2017...   
3  7308210929  https://fayetteville.craigslist.org/ctd/d/rale...   
4  7303797340  https://knoxville.craigslist.org/ctd/d/knoxvil...   

         region                           region_url  price  year  \
0   chattanooga   https://chattanooga.craigslist.org  54990  2020   
1  north jersey     https://newjersey.craigslist.org  16942  2016   
2  reno / tahoe          https://reno.craigslist.org  35590  2017   
3  fayetteville  https://fayetteville.craigslist.org  14500  2013   
4     knoxville     https://knoxville.craigslist.org  14590  2012   

  manufacturer                   model    fuel  odometer title_status  \
0          ram  2500 crew cab big horn  diesel     27442        clean   
1         ford    explorer 4wd 4dr xlt   other     60023        clean   
2   volkswagen        golf r hatchback     gas     14048        clean   
3       toyota                    rav4     gas    117291        clean   
4          bmw  1 series 128i coupe 2d   other     80465        clean   

  transmission                                          image_url  \
0        other  https://images.craigslist.org/00N0N_1xMPvfxRAI...   
1    automatic  https://images.craigslist.org/00x0x_26jl9F0cnL...   
2        other  https://images.craigslist.org/00y0y_eeZjWeiSfb...   
3    automatic  https://images.craigslist.org/00606_iGe5iXidib...   
4        other  https://images.craigslist.org/00F0F_5UAXmOzC18...   

                                         description state        lat  \
0  Carvana is the safer way to buy a car During t...    tn  35.060000   
1  ***Call Us for more information at: 201-635-14...    nj  40.821805   
2  Carvana is the safer way to buy a car During t...    ca  33.779214   
3  2013 Toyota RAV4 XLE 4dr SUV     Offered by: R...    nc  35.715954   
4  Carvana is the safer way to buy a car During t...    tn  35.970000   

        long              posting_date price_category  \
0 -85.250000  2021-04-17T12:30:50-0400           high   
1 -74.061962  2021-05-03T15:40:21-0400         medium   
2 -84.411811  2021-04-28T03:52:20-0700           high   
3 -78.655304  2021-04-17T10:08:57-0400         medium   
4 -83.940000  2021-04-08T15:10:56-0400         medium   

                        date  
0  2021-04-17 16:30:50+00:00  
1  2021-05-03 19:40:21+00:00  
2  2021-04-28 10:52:20+00:00  
3  2021-04-17 14:08:57+00:00  
4  2021-04-08 19:10:56+00:00

In [87]:
# Ваш код здесь
df_old = df_old.copy()
df_old = df_old.drop(['price', 'date', 'posting_date', 'state', 'description', 'image_url', 'transmission', 'title_status', 'fuel', 'model', 'manufacturer', 'region_url', 'region', 'url'], axis=1)
x = df_old.drop(['price_category'], axis=1)
y = df_old['price_category']

In [88]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [89]:
rf_tuned = RandomForestClassifier(random_state = 50, n_estimators = 700, min_samples_split = 2, min_samples_leaf = 1, max_features = 'sqrt', max_depth = None, bootstrap = False)
rf_tuned.fit(x_train, y_train)

predicted_train = rf_tuned.predict(x_train)
predicted_test = rf_tuned.predict(x_test)

print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))

1.0
0.6316701316701316


In [90]:
import numpy as np

features = x_train.columns
importances = rf_tuned.feature_importances_
indices = np.argsort(importances)

In [91]:
[features[i] for i in indices][-3:]

['id', 'year', 'odometer']